### ISSUE TITLE
Validation broken when using option/optional arguments

### ISSUE THREAD

**Issue by sandrwich** [OkaeriPoland/okaeri-commands#9]
Related to https://github.com/OkaeriPoland/okaeri-validator/issues/3

```
eu.okaeri.validator.exception.ValidatorException: @Pattern is not applicable for class eu.okaeri.commands.service.Option (to validate #toString() output set useToString=true) [name]
	at eu.okaeri.validator.provider.PatternProvider.validate(PatternProvider.java:39) ~[okaeri-api.jar:?]
	at eu.okaeri.validator.provider.PatternProvider.validate(PatternProvider.java:14) ~[okaeri-api.jar:?]
	at eu.okaeri.validator.provider.ValidationProvider.validate(ValidationProvider.java:44) ~[okaeri-api.jar:?]
	at eu.okaeri.validator.OkaeriValidator.lambda$validateParameter$5(OkaeriValidator.java:98) ~[okaeri-api.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at eu.okaeri.validator.OkaeriValidator.validateParameter(OkaeriValidator.java:99) ~[okaeri-api.jar:?]
	at eu.okaeri.commands.injector.OkaeriParameterValidationHandler.validate(OkaeriParameterValidationHandler.java:34) ~[okaeri-api.jar:?]
	at eu.okaeri.commands.OkaeriCommands.invocationPrepare(OkaeriCommands.java:580) ~[okaeri-api.jar:?]
	at eu.okaeri.commands.bukkit.CommandsBukkit.handleExecution(CommandsBukkit.java:269) ~[okaeri-api.jar:?]
	at eu.okaeri.commands.bukkit.CommandsBukkit.lambda$executeCommand$1(CommandsBukkit.java:233) ~[okaeri-api.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1765]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1765]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by dasavick** [comment]
Cannot believe this is still broken!111

**Comment by P3ridot** [comment]
just fix it? bro it's that simple
